### ISSUE TITLE
Channels are been overwritten when we use the same name.

### ISSUE THREAD

**Issue by malave** [samtecspg/conveyor#132] opened 2018-04-03 11:13 UTC
The name validation is failing during channel creation and this is causing the existing channels to be overwritten.

**Comment by wrathagom** [comment] 2018-04-05 12:16
Duplicate of #99 doesn't the name validation happen in the API? not the UI?

**Closed by wrathagom** 2018-04-05 12:16 UTC
Labels: bug, plugin

**Comment by malave** [comment] 2018-04-05 13:30
@wrathagom: Correct, we need to check why this is not happening.
